### ISSUE TITLE
Add ScreenShots

### ISSUE THREAD

**Issue by OmarFatahiDev** [saman-karashi/Taskmanagment#1]
hi saman! how ar u dooin??!

why u dont add pics of your project??!!

when ur down, take a picture of ur project!!

**Comment by saman-karashi** [comment]
Hi Omar , i'm good thanks.

The reason i didn't add any pics because it still needs lots of work.Right now i just make reusable components in order to make the developing process 10x faster.

**Comment by OmarFatahiDev** [comment]
uhm i understand u... good luck man...


katek tawawt krd, teikha.. bo awakanish harwaha
